### ISSUE TITLE
特别放送没问题，但是主要内容出现报错

### ISSUE THREAD

**Issue by yiqijiu** [jjeejj/geektime2pdf#14]
(node:9388) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.closeTarget): Target closed.                    at Promise (C:\Users\sy\geektime2pdf\node_modules\puppeteer\lib\Connection.js:74:56)                                    at new Promise (<anonymous>)                                                                                            at Connection.send (C:\Users\sy\geektime2pdf\node_modules\puppeteer\lib\Connection.js:73:12)                            at Page.close (C:\Users\sy\geektime2pdf\node_modules\puppeteer\lib\Page.js:991:38)                                      at Page.<anonymous> (C:\Users\sy\geektime2pdf\node_modules\puppeteer\lib\helper.js:111:23)                              at generaterPdf (C:\Users\sy\geektime2pdf\generaterPdf.js:38:27)                                                    (node:9388) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

**Comment by jjeejj** [comment]
@yiqijiu  哪一篇文章？

**Comment by yiqijiu** [comment]
你好,数据中台实战的所有文章,
