### ISSUE TITLE
TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded相关异常

### ISSUE THREAD

**Issue by chaoxuanxiaok** [jjeejj/geektime2pdf#20]
当我代码执行到如下部分时，
`await page.setContent(utils.renderEjsArticle2Html(data, options)); `
抛出了超时异常，
 ```
generater pdf err { TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (E:\work_space\Java\geektime2pdf\node_modules\puppeteer\lib\LifecycleWatcher.js:143:21)
  -- ASYNC --
    at Frame.<anonymous> (E:\work_space\Java\geektime2pdf\node_modules\puppeteer\lib\helper.js:110:27)
    at Page.setContent (E:\work_space\Java\geektime2pdf\node_modules\puppeteer\lib\Page.js:647:42)
    at Page.<anonymous> (E:\work_space\Java\geektime2pdf\node_modules\puppeteer\lib\helper.js:111:23)
    at generaterPdf (E:\work_space\Java\geektime2pdf\generaterPdf.js:28:20)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError' }
```
请问这种情况应该如何避免，我尝试结合网上的意见，对代码进行调整，修改为
`await page.goto(`data:text/html,${utils.renderEjsArticle2Html(data, options)}`, { waitUntil: 'networkidle2' });`
如此一来虽然不再报错，但是生成的pdf是空白文档，希望作者能帮忙答疑一下，谢谢

**Comment by chaoxuanxiaok** [comment]
翻找到之前已经有过类似的issue，先关闭，不好意思
