### ISSUE TITLE
generater pdf err TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded

### ISSUE THREAD

**Issue by liyang85** [jjeejj/geektime2pdf#6]
今天下载的两个课程都出现了如题所述的报错。

- 《Kafka核心技术与实战》：3 次报错。
- 《数据结构与算法之美》：1 次报错。

报错的章节最终未能生成 PDF 文件，其它没有报错的章节仍然能够正常生成 PDF。

详细错误信息如下：

```
开篇词 | 从今天起，跨过“数据结构与算法”这道坎
开始获取  https://time.geekbang.org/column/article/39922 评论
结束获取  https://time.geekbang.org/column/article/39922 评论 总评论数为 641
generater pdf start
generater pdf err TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at /Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/LifecycleWatcher.js:143:21
  -- ASYNC --
    at Frame.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.setContent (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Page.js:647:42)
    at Page.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:111:23)
    at generaterPdf (/Users/liyang/github_projects/geektime2pdf/generaterPdf.js:28:20)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:62:13)
    at async getColumnArticleList (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:85:5) {
  name: 'TimeoutError'
}
(node:4383) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.closeTarget): Target closed.
    at /Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Connection.js:74:56
    at new Promise (<anonymous>)
    at Connection.send (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Connection.js:73:12)
    at Page.close (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Page.js:991:38)
    at Page.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:111:23)
    at generaterPdf (/Users/liyang/github_projects/geektime2pdf/generaterPdf.js:38:27)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:62:13)
    at async getColumnArticleList (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:85:5)
(node:4383) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by liyang85** [comment]
```
03 | Kafka只是消息引擎系统吗？
开始获取  https://time.geekbang.org/column/article/99797 评论
结束获取  https://time.geekbang.org/column/article/99797 评论 总评论数为 33
generater pdf start
generater pdf err TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at /Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/LifecycleWatcher.js:143:21
  -- ASYNC --
    at Frame.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.setContent (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Page.js:647:42)
    at Page.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:111:23)
    at generaterPdf (/Users/liyang/github_projects/geektime2pdf/generaterPdf.js:28:20)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:62:13)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getColumnArticleList (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:85:5) {
  name: 'TimeoutError'
}
(node:4868) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.closeTarget): Target closed.
    at /Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Connection.js:74:56
    at new Promise (<anonymous>)
    at Connection.send (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Connection.js:73:12)
    at Page.close (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Page.js:991:38)
    at Page.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:111:23)
    at generaterPdf (/Users/liyang/github_projects/geektime2pdf/generaterPdf.js:38:27)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:62:13)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
  -- ASYNC --
    at Page.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:110:27)
    at generaterPdf (/Users/liyang/github_projects/geektime2pdf/generaterPdf.js:38:27)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:62:13)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getColumnArticleList (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:85:5)
(node:4868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by liyang85** [comment]
```
32 | KafkaAdminClient：Kafka的运维利器
开始获取  https://time.geekbang.org/column/article/118319 评论
结束获取  https://time.geekbang.org/column/article/118319 评论 总评论数为 12
generater pdf start
generater pdf err TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at /Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/LifecycleWatcher.js:143:21
  -- ASYNC --
    at Frame.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.setContent (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Page.js:647:42)
    at Page.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:111:23)
    at generaterPdf (/Users/liyang/github_projects/geektime2pdf/generaterPdf.js:28:20)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:62:13)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
  -- ASYNC --
    at Page.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:110:27)
    at generaterPdf (/Users/liyang/github_projects/geektime2pdf/generaterPdf.js:28:20)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:62:13)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17) {
  name: 'TimeoutError'
}
(node:4868) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.closeTarget): Target closed.
    at /Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Connection.js:74:56
    at new Promise (<anonymous>)
    at Connection.send (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Connection.js:73:12)
    at Page.close (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Page.js:991:38)
    at Page.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:111:23)
    at generaterPdf (/Users/liyang/github_projects/geektime2pdf/generaterPdf.js:38:27)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:62:13)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
  -- ASYNC --
    at Page.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:110:27)
    at generaterPdf (/Users/liyang/github_projects/geektime2pdf/generaterPdf.js:38:27)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:62:13)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
(node:4868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by liyang85** [comment]
```
33 | Kafka认证机制用哪家？
开始获取  https://time.geekbang.org/column/article/118347 评论
结束获取  https://time.geekbang.org/column/article/118347 评论 总评论数为 9
generater pdf start
generater pdf err TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at /Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/LifecycleWatcher.js:143:21
  -- ASYNC --
    at Frame.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.setContent (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Page.js:647:42)
    at Page.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:111:23)
    at generaterPdf (/Users/liyang/github_projects/geektime2pdf/generaterPdf.js:28:20)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:62:13)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
  -- ASYNC --
    at Page.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:110:27)
    at generaterPdf (/Users/liyang/github_projects/geektime2pdf/generaterPdf.js:28:20)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:62:13)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17) {
  name: 'TimeoutError'
}
(node:4868) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.closeTarget): Target closed.
    at /Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Connection.js:74:56
    at new Promise (<anonymous>)
    at Connection.send (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Connection.js:73:12)
    at Page.close (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/Page.js:991:38)
    at Page.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:111:23)
    at generaterPdf (/Users/liyang/github_projects/geektime2pdf/generaterPdf.js:38:27)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:62:13)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
  -- ASYNC --
    at Page.<anonymous> (/Users/liyang/github_projects/geektime2pdf/node_modules/puppeteer/lib/helper.js:110:27)
    at generaterPdf (/Users/liyang/github_projects/geektime2pdf/generaterPdf.js:38:27)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:62:13)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
    at async getNextColumnArticleUrl (/Users/liyang/github_projects/geektime2pdf/columnArticleList.js:79:17)
(node:4868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by liyang85** [comment]
自行调整超时时间之后，再也没有出现 TimeoutError。

```bash
$ vim node_modules/puppeteer/lib/TimeoutSettings.js

// Default value
// const DEFAULT_TIMEOUT = 30000;

// New value
const DEFAULT_TIMEOUT = 60000;
```

**Comment by chaoxuanxiaok** [comment]
亲测有效，十分感谢
