### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by mari1995** [jjeejj/geektime2pdf#8]
generater pdf err { Error: ENOENT: no such file or directory, open 'D:\mario\github\geektime2pdf\geektime_Kafka核心技术与实战\17 | 消费者组重平衡能避免吗？.pdf'
  -- ASYNC --
    at Page.<anonymous> (D:\mario\github\geektime2pdf\node_modules\puppeteer\lib\helper.js:110:27)
    at generaterPdf (D:\mario\github\geektime2pdf\generaterPdf.js:31:20)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'D:\\mario\\github\\geektime2pdf\\geektime_Kafka核心技术与实战\\17 | 消费者组重平衡能避免吗？.pdf' }
(node:14764) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.closeTarget): Target closed.
    at Promise (D:\mario\github\geektime2pdf\node_modules\puppeteer\lib\Connection.js:74:56)
    at new Promise (<anonymous>)
    at Connection.send (D:\mario\github\geektime2pdf\node_modules\puppeteer\lib\Connection.js:73:12)
    at Page.close (D:\mario\github\geektime2pdf\node_modules\puppeteer\lib\Page.js:991:38)
    at Page.<anonymous> (D:\mario\github\geektime2pdf\node_modules\puppeteer\lib\helper.js:111:23)
    at generaterPdf (D:\mario\github\geektime2pdf\generaterPdf.js:38:27)
(node:14764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)

**Comment by jjeejj** [comment]
报错信息提示的很清楚了 **no such file or directory, open**，你可以检查一下

**Comment by mari1995** [comment]
> 报错信息提示的很清楚了**没有这样的文件或目录，打开**，你可以检查一下

问题是文件夹是存在的，文件不是自动生成的吗？

**Comment by mari1995** [comment]
> 报错信息提示的很清楚了 **no such file or directory, open**，你可以检查一下

查到是特殊字符引起的创建文件失败
